name: Build WirewayAudioFix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Theos & Legacy SDKs
        uses: theos/action@v1
        with:
          theos-sdks: 'https://github.com/theos/sdks'
          theos-sdks-ref: 'master'

      - name: Fix SDK module maps for modern Clang
        run: |
          find $THEOS/sdks -name "module.map" -exec bash -c 'mv "$1" "${1%.map}.modulemap"' _ {} \;

      - name: Build Package
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WirewayAudioFix-DEB
          path: |
            **/packages/*.deb
            **/*.deb
